name: 'Playwright E2E Testing'

trigger:
- master
- dev

variables:
- name: npm_config_cache
  value: $(Pipeline.Workspace)/.npm

stages:
- stage: e2e_testing_stage
  displayName: 'E2E Testing'
  jobs:
  - job: e2e_testing_job
    pool:
      vmImage: 'ubuntu-latest'
    displayName: 'Run E2E tests'
    steps:
      - task: NodeTool@0
        displayName: 'Use Node 12.x'
        inputs:
          versionSpec: 12.x
          
      - script: |
          npm ci
          displayName: 'Install project dependencies'
      - bash: |
          npm test
          displayName: 'Run the tests'
  
      - task: PublishTestResults@2
        displayName: 'Publish the test reports'
        inputs:
         testResultsFiles: '**/reports/junit.xml'
        condition: succeededOrFailed()
